exclude: [scss, config.rb, README.md, app.js, script.js, modernizr-2.6.2.js, lte-ie7.js]
site_name: The Ring Falcon Trilogy
tagline: An Epically Awesome Community Film
auto: true
css: /css/global.css
